a = input('Digite algo: ')
print('O tipo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isalnum())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está em maiusculas?', a.isupper())
print('Está em minúscula?', a.islower())
print('Está capitalizada?', a.istitle())